---
name: IPC-PerlSSH
version: 0.14
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: execute remote perl code over an SSH link
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IPC::Open2: 0
build_requires:
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  Test::Exception: 0
  Test::More: 0
provides:
  IPC::PerlSSH:
    file: lib/IPC/PerlSSH.pm
    version: 0.14
  IPC::PerlSSH::Base:
    file: lib/IPC/PerlSSH/Base.pm
    version: 0.14
  IPC::PerlSSH::Library:
    file: lib/IPC/PerlSSH/Library.pm
    version: 0.14
  IPC::PerlSSH::Library::FS:
    file: lib/IPC/PerlSSH/Library/FS.pm
    version: 0.14
  IPC::PerlSSH::Library::IO:
    file: lib/IPC/PerlSSH/Library/IO.pm
    version: 0.14
  IPC::PerlSSH::Library::Run:
    file: lib/IPC/PerlSSH/Library/Run.pm
    version: 0.14
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
