---
name: IPC-PerlSSH
version: 0.08
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: a class for executing remote perl code over an SSH link
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IPC::Open2: 0
build_requires:
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
provides:
  IPC::PerlSSH:
    file: lib/IPC/PerlSSH.pm
    version: 0.08
  IPC::PerlSSH::Base:
    file: lib/IPC/PerlSSH/Base.pm
    version: 0.08
  IPC::PerlSSH::Library:
    file: lib/IPC/PerlSSH/Library.pm
    version: 0.08
  IPC::PerlSSH::Library::FS:
    file: lib/IPC/PerlSSH/Library/FS.pm
    version: 0.08
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
