# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPC-PerlSSH
version:      0.02
version_from: lib/IPC/PerlSSH.pm
installdirs:  site
requires:
    IPC::Open2:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
